version: "3.2"

# FHIR Appliance Quickstart for Windows containers

services:
  fhir-appliance-db:
    build:
      context: .\sql
      dockerfile: Dockerfile
    container_name: fhir-appliance-db
    hostname: localhost
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: Pa55w0rd1!
      MSSQL_PID: Developer
    ports:
      - 1433:1433
    volumes:
      - .\data:C:\SQLData

  fhir-appliance:
    image: synaneticsltd/synfhir-store:windows-2019-latest
    restart: always
    container_name: fhir-appliance
    environment:
      # Settings required by moleculer (not configurable)
      - METRICSENABLE=false
      - NAMESPACE=fhir-appliance
      - NODE_ENV=development
      - SERVICEDIR=services
      - SERVICES=**/*.service.js
    env_file:
      - .env
    ports:
      # Public endpoint (https)
      # Map 443 of the host to 443 in the container if using SSL
      - 443:443
      # Integration endpoint (http)
      - 8300:8300
    ##    depends_on:
    ##      - fhir-appliance-db
    volumes:
      # Copy .pem formatted SSL certificates: certificate, private key, passphrase (optional) and, if using mutal tls, root CA certificate to ssl if securing the endpoint
      - ..\shared\ssl:C:\app\ssl
      # If using public key based JSON web token verification then copy public key of CA to keys folder (see environment file for information)
      - ..\shared\jwt:C:\app\jwt
      # If publishing patient registrations to regional PIX service then copy your client certificates and keys to this folder
      - ..\shared\pix:C:\app\pix
    networks:
      - default
